"""

This is a script which facilitates the extraction of competency questions (CQs) from schemas using a large language model (LLM).

"""

import prompts as p
import os
import re
import utils
import logging
import time
import notion_utils
import json
import ast

from utils import get_key
from interfaces import GeminiLLM, OpenAILLM
from schema2cq import PromptBuilder
from notion_client import Client
from tqdm import tqdm

geminikey = get_key("gemini")
openai_key = get_key("openai")

LLMDB = get_key("notionllmdb")
NOTION_TOKEN = get_key("notionkey")
NOTION_PAGE_ID = get_key("notionpage")  # This should be your Notion page ID
NOTION_DATABASE_ID = get_key("notiondb")  # This should be your Notion database ID

notion = Client(auth=NOTION_TOKEN)
logging.basicConfig(level=logging.INFO)
logging.getLogger("httpx").setLevel(logging.WARNING)  # Suppress httpx warnings

## -- Use a config dictionary to store the configuration parameters -- ##
config = {
    "temperature": 0.2,
    "role": p.SYSTEM_ROLE_A,
    "gemini_model": "models/gemini-2.5-flash",
    "out_definition": p.CQ_DEFINITION_A,
    "out_examples": p.CQ_EXAMPLE_A,
    "out_instruction": p.CQ_INSTRUCTION_C,
    "limit": "Do not generate more than 150 Competency Questions." # Default limit for the number of competency questions
}

## -- Get both the AnIML core schema and the AnIML technique schema 
# --  and hence the combined schemas 
animl_core_schema, animl_technique_schema = utils.getSchemas()
combined_schemas = animl_core_schema + "\n" + animl_technique_schema



def configure_prompt(role: str = config["role"],
                     out_definition: str = config["out_definition"],
                     out_examples: str = config["out_examples"],
                     out_instruction: str = config["out_instruction"],
                     limit: int = config["limit"],
                     ignore_schemas: bool = False) -> str:
    """
    
    Configures the prompt for competency question extraction.

    Args:
        role (str): The role to use for the model.
        out_definition (str): The output definition for competency questions.
        out_examples (str): The output examples for competency questions.
        out_instruction (str): The output instruction for competency questions.
        limit (int): The maximum number of competency questions to extract.

    Returns:
        str: The configured prompt for competency question extraction.
    """

    prompt_builder = PromptBuilder(
        role=role,
        out_definition=out_definition,
        out_examples=out_examples,
        out_instruction=out_instruction,
        limit=limit
    )

    prompt = prompt_builder.get_prompt(
        raw_data=combined_schemas if not ignore_schemas else "",
        include_role=False,
    )

    return prompt
    


def run_cq_extraction(model: object, prompt) -> list:
    """
    
    Runs the competency question extraction using the specified model and prompt.

    Args:
        model (object): An instance of the LLM to use for generating competency questions.
        prompt (str): The prompt to use for generating competency questions.

    Returns:
        list: A list of competency questions generated by the model.
    
    """

    response = model.generate(prompt)

    return response

def cq_to_txt(cqs: list, newfilepath: str) -> None:
    """
    
    Writes the competency questions (CQs) to a text file.

    Args:
        cqs (list): A list of competency questions.
        newfilepath (str): The path to the file where the competency questions will be written.

    Returns:
        None: The function writes the competency questions to the specified file.

    Note: 
        newfilepath should be a valid file path where you want to save the competency questions (ie in the file).
    
    """


    #path = os.path.join(os.getcwd(), "..", "assets", "cqs", "g02_cqs.txt")

    with open(newfilepath, "w") as f:
        for q in cqs:
            f.write(q + "\n")

    logging.info(f"Competency questions written to {newfilepath}")
    

def get_llm_instance(model_name: str, api_key: str, 
                     role = config["role"], temperature = config["temperature"]) -> object:
    """
    Returns an instance of the LLM based on the model name and API key.

    Args:
        model_name (str): The name of the model to use.
        api_key (str): The API key for the model.
        role (str): The role to use for the model.
        temperature (float): The temperature to use for the model.

    Returns:
        GeminiLLM or OpenAILLM: An instance of the appropriate LLM class.
    """

    return GeminiLLM(model=model_name, api_key=api_key, role=role, temperature=temperature) \
    if "gemini" in model_name.lower() else OpenAILLM(model=model_name, api_key=api_key, role=role, temperature=temperature)

def save_llm_insatance(cqset: str, instance=[], isReformulated=False) -> None:
    """
    
    Save the LLM instance to a file.

    Args:
        cqset (str): The name of the competency question set.
        instance (list): A list to store the LLM instance details.

    Returns:
        None: The function saves the LLM instance to the specified file.
    
    Note: This is a placeholder function, as saving an LLM instance directly is not typically supported.
    
    """
    filepath = os.path.join(os.getcwd(), "assets", "cqs", "llm_instances.json")

    instance.append({
        "model": config["gemini_model"],
        "role": config["role"],
        "temperature": config["temperature"],
        "cqset": cqset,
        "isReformulated": isReformulated
    })

    with open(filepath, "a") as f:
        json.dump(instance, f, indent=2, ensure_ascii=False)

    print(f"\nLLM instance saved to {filepath}")

def clean_llm_output(cqs) -> list:
    """
    Clean the output of the competency questions (CQs) from the LLM by ensuring each item is a plain string (no quotes, no formatting artifacts).
    Accepts a list of strings and returns a cleaned list, one question per line.

    Args:
        cqs (list): The competency questions as a list of strings (possibly with quotes or artifacts).

    Returns:
        list: A list of cleaned competency questions (plain text, one per line).
    """

    if isinstance(cqs, str):
        try:
            parsed = ast.literal_eval(cqs)
            if isinstance(parsed, list):
                return [str(q).strip().strip("'\"") for q in parsed if str(q).strip()]
            
            else:
                return [str(parsed).strip().strip("'\"")]
            
        except Exception:
            return [cqs.strip().strip("'\"")]
        
    elif isinstance(cqs, list):
        return [str(q).strip().strip("'\"") for q in cqs if str(q).strip()]
    
    else:
        return []

def getconfigurations():
    """
    
    Get the current configuration dictionary.

    Returns:
        dict: The current configuration dictionary.
    
    """

    return config

def update_config(**kwargs) -> None:
    """
    
    Update the global config dictionary with new values. Resolves the keys to their correct types and values.

    Args:
        **kwargs: Key-value pairs to update the config dictionary.
    
    """

    for k, v in kwargs.items():

        ## -- Cast known keys to their correct types
        if k == "temperature":
            config[k] = float(v)

        elif k in ["out_definition", "out_examples", "out_instruction", "role"]:
            if v == "":
                config[k] = "" ## -- If the value is an empty string, set it to an empty string
            elif hasattr(p, v):
                config[k] = getattr(p, v)
        else:
            config[k] = v

def get_generation_number() -> str:
    """
    
    Get a string for the last generation and increment for a new one using a regex pattern to match the generation files in the assets/cqs directory.

    Returns:
        str: A string representing the next generation number, formatted as "gXX_cqs", where XX is the generation number.

    """

    max_gen = 0
    pattern = re.compile(r"g(\d+)_(cqs|reformulated)\.txt$")

    for fname in os.listdir(os.path.join(os.getcwd(), "assets", "cqs")):
        matchname = pattern.search(fname)
        if matchname:
            gen_number = int(matchname.group(1))
            if gen_number > max_gen:
                max_gen = gen_number

    ## -- Return the next generation string
    return f"g{max_gen + 1:02d}_cqs"


if __name__ == "__main__":

    os.system("CLS")

    decided = False
    while not decided:
        args = input("\nUpdate config? (e.g temperature = ..., role = ...)\npress <enter> to skip\nType help for help on options: ").strip()

        if args.lower() == "help":
            utils.help_config()
            time.sleep(2)

        elif args and args.lower() != "none":
            update_config(**{k.strip(): v.strip() for k, v in (item.split("=", 1) for item in args.split(",") if "=" in item)})
            decided = True

        elif args.lower() == "none" or not args:
            decided = True

    ## -- Get the LLM instance
    model = get_llm_instance(config["gemini_model"], api_key=geminikey, role=config["role"], temperature=config["temperature"])
    
    ## -- Run the competency question extraction
    cqs = run_cq_extraction(model, configure_prompt())
    
    ## -- Clean the output
    cleaned_cqs = clean_llm_output(cqs)

    print("There are {} competency questions extracted.".format(len(cleaned_cqs)))
    
    ## -- Write the cleaned CQs to a file
    cq_to_txt(cleaned_cqs, os.path.join(os.getcwd(), "assets", "cqs", "g02_cqs.txt")) \
        if (choice := input("Do you want to write the CQs to a file? (yes/no): ").strip().lower()) == "yes" else None
    
    competency_questions = notion_utils.get_cqs_from_file(os.path.join(os.getcwd(), "assets", "cqs", "trial_cqs.txt"))
    
    # Write each competency question to the Notion database
    for cq in tqdm(competency_questions):
        notion_utils.write_row(notion, NOTION_DATABASE_ID, "CQ", cq)
    
    print("Competency questions written to Notion database.")