"""

This is a script which facilitates the extraction of competency questions (CQs) from schemas using a large language model (LLM).

"""

import prompts as p
import os
import utils
import logging
import json
import ast
import re

from utils import get_key
from interfaces import GeminiLLM, OpenAILLM
from schema2cq import PromptBuilder
from notion_client import Client
from tqdm import tqdm

geminikey = get_key("gemini") # This should be your Gemini API key
openai_key = get_key("openai") # This should be your OpenAI API key

LLMDB = get_key("notionllmdb") 
NOTION_TOKEN = get_key("notionkey") # This should be your Notion integration token
NOTION_PAGE_ID = get_key("notionpage")  # This should be your Notion page ID
NOTION_DATABASE_ID = get_key("notiondb")  # This should be your Notion database ID

notion = None

## -- Lazy load
def get_notion_client():
    global notion
    if notion is None:
        notion = Client(auth=get_key("notionkey"))
    return notion

logging.basicConfig(level=logging.INFO)
logging.getLogger("httpx").setLevel(logging.WARNING)  # Suppress httpx warnings

# --- LAZY PROMPTS LOADING ---
_prompts = None
def get_prompts():
    global _prompts
    if _prompts is None:
        import prompts as p
        _prompts = p
    return _prompts

# --- CONFIG DICTIONARY WITH LAZY PROMPTS ---
config = {
    "temperature": 0.2,
    "role": lambda: get_prompts().SYSTEM_ROLE_A,
    "gemini_model": "models/gemini-2.5-flash",
    "out_definition": lambda: get_prompts().CQ_DEFINITION_A,
    "out_examples": lambda: get_prompts().CQ_EXAMPLE_A,
    "out_instruction": lambda: get_prompts().CQ_INSTRUCTION_C,
    "limit": "Generate around 100 competency questions."
}

def get_config_value(key):
    value = config[key]
    return value() if callable(value) else value



def configure_prompt(role=None, out_definition=None, out_examples=None, out_instruction=None, limit=None,
                    schema=None, schema_names=None, ignore_schemas=False) -> str:
    """
    Configures the prompt for competency question extraction.

    Args:
        role (str): The role to use in the prompt.
        out_definition (str): The output definition for the prompt.
        out_examples (str): The output examples for the prompt.
        out_instruction (str): The output instruction for the prompt.
        limit (str): The limit for the number of competency questions to generate.
        schema (str): The schema to use in the prompt.
        schema_names (list): The names of the schemas to use in the prompt.
        ignore_schemas (bool): Whether to ignore schemas in the prompt.
    Returns:
        str: The configured prompt.
    """


    role = role or get_config_value("role")
    out_definition = out_definition or get_config_value("out_definition")
    out_examples = out_examples or get_config_value("out_examples")
    out_instruction = out_instruction or get_config_value("out_instruction")
    limit = limit or get_config_value("limit")

    prompt_builder = PromptBuilder(
        role=role,
        out_definition=out_definition,
        out_examples=out_examples,
        out_instruction=out_instruction,
        limit=limit
    )

    prompt = prompt_builder.get_prompt(
        raw_data=schema if not ignore_schemas else "",
        include_role=False,
    )

    return prompt, schema, schema_names


def run_cq_extraction(model: object, prompt) -> list:
    """
    
    Runs the competency question extraction using the specified model and prompt.

    Args:
        model (object): An instance of the LLM to use for generating competency questions.
        prompt (str): The prompt to use for generating competency questions.

    Returns:
        list: A list of competency questions generated by the model.
    
    """

    response = model.generate(prompt)
    return response


def cq_to_txt(cqs: list, newfilepath: str) -> None:
    """
    
    Writes the competency questions (CQs) to a text file.

    Args:
        cqs (list): A list of competency questions.
        newfilepath (str): The path to the file where the competency questions will be written.

    Returns:
        None: The function writes the competency questions to the specified file.

    Note: 
        newfilepath should be a valid file path where you want to save the competency questions (ie in the file).
    
    """

    with open(newfilepath, "w") as f:
        for q in cqs:
            f.write(q + "\n")

    logging.info(f"Competency questions written to {newfilepath}")
    

def get_llm_instance(model_name, api_key, role=None, temperature=None) -> object:
    role = role or get_config_value("role")
    temperature = temperature if temperature is not None else config["temperature"]
    return GeminiLLM(model=model_name, api_key=api_key, role=role, temperature=temperature) \
        if "gemini" in model_name.lower() else OpenAILLM(model=model_name, api_key=api_key, role=role, temperature=temperature)

def save_llm_insatance(cqset: str, instance=[], isReformulated=False) -> None:
    """
    
    Save the LLM instance to a file for debugging purposes.

    Args:
        cqset (str): The name of the competency question set.
        instance (list): A list to store the LLM instance details.
        isReformulated (bool): Whether the instance is a reformulated set of competency questions.

    Returns:
        None: The function saves the LLM instance to the specified file.
    
    Note: This is mainly for debugging purposes, it saves the LLM instance details to a JSON file to
          cross reference to the Notion LLM database.
    
    """
    filepath = os.path.join(os.getcwd(), "assets", "cqs", "llm_instances.json")

    instance.append({
        "model": config["gemini_model"],
        "role": config["role"],
        "temperature": config["temperature"],
        "cqset": cqset,
        "isReformulated": isReformulated
    })

    with open(filepath, "a") as f:
        json.dump(instance, f, indent=2, ensure_ascii=False)

    print(f"\nLLM instance saved to {filepath}")

def remove_local_ids_from_reformulations(cqs: list) -> list:
    """
    Remove local IDs from reformulated competency questions (CQs).

    Args:
        cqs (list): A list of reformulated competency questions with local IDs.

    Returns:
        list: A list of reformulated competency questions without local IDs.
    """
    if not cqs:
        return []

    cleaned = []
    # Remove up to two colon-separated prefixes (robust for "(ID: 237):", "ID: 42:", "237:", etc.)
    prefix_re = re.compile(r'^(?:[^:]*:\s*){1,2}', flags=re.UNICODE)

    for item in cqs:
        # extract candidate text
        if isinstance(item, dict):
            # prefer common keys that may contain the reformulated text
            text = None
            for key in ("reformulated", "reformulation", "text", "cq", "question"):
                if key in item and isinstance(item[key], str):
                    text = item[key]
                    break
            if text is None:
                # fallback: join values that are strings or stringify entire dict
                vals = [str(v) for v in item.values() if isinstance(v, (str, int, float))]
                text = " ".join(vals) if vals else json.dumps(item, ensure_ascii=False)
        else:
            text = str(item)

        # strip up to two colon-delimited prefixes, then trim common leftover punctuation/spaces
        cleaned_text = prefix_re.sub("", text).strip()
        cleaned_text = cleaned_text.lstrip(" \t:)-.[]")

        cleaned.append(cleaned_text)

    return cleaned



def clean_llm_output(cqs) -> list:
    """
    Clean the output of the competency questions (CQs) from the LLM by ensuring each item is a plain string (no quotes, no formatting artifacts).
    Accepts a list of strings and returns a cleaned list, one question per line.

    Args:
        cqs (list): The competency questions as a list of strings (possibly with quotes or artifacts).

    Returns:
        list: A list of cleaned competency questions (plain text, one per line).
    """

    ## -- Instance handling for type
    if isinstance(cqs, str):
        try:
            parsed = ast.literal_eval(cqs)
            if isinstance(parsed, list):
                return [str(q).strip().strip("'\"") for q in parsed if str(q).strip()]
            
            else:
                return [str(parsed).strip().strip("'\"")]
            
        except Exception:
            return [cqs.strip().strip("'\"")]
        
    elif isinstance(cqs, list):
        return [str(q).strip().strip("'\"") for q in cqs if str(q).strip()]
    
    else:
        return []

def getconfigurations() -> dict:
    """
    
    Get the current configuration dictionary.

    Returns:
        dict: The current configuration dictionary.
    
    """

    return config

def update_config(**kwargs):
    """
    Update the configuration dictionary with the provided keyword arguments.
    Args:
        **kwargs: Keyword arguments to update the configuration dictionary.
    """
    
    p = get_prompts()
    for k, v in kwargs.items():
        if k == "temperature":
            config[k] = float(v)
        elif k in ["out_definition", "out_examples", "out_instruction", "role"]:
            if v == "":
                config[k] = ""
            elif hasattr(p, v):
                attr_value = getattr(p, v)
                config[k] = (lambda val=attr_value: val)
            else:
                config[k] = v
        else:
            config[k] = v